name: Deno CI

on:
  push:
    branches: [main, esm-first]
  pull_request:
    branches: [main, esm-first]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ["1.17.2"]

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version}}

      - run: make test
