name: Deno CI

on:
  push:
    branches: [main, squirrel]
  pull_request:
    branches: [main, squirrel]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: ["1.25.1"]

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version}}

      - run: deno task test
